{% set name = "sphinxawesome-theme" %}
{% set version = "6.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sphinxawesome_theme-{{ version }}.tar.gz
  sha256: b76e41fc56fcbf6691172530e61bcf352623eb3298114ba3e323fec5d792e07b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry
    - pip
  run:
    - python >={{ python_min }}
    - sphinx >=7.2.0,<7.3
    - beautifulsoup4 >=4.9.1,<5.0.0

test:
  imports:
    - sphinxawesome_theme
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://sphinxawesome.xyz
  summary: An awesome theme for the Sphinx documentation generator
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apmorton
