{% set name = "sphinxawesome-theme" %}
{% set version = "5.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinxawesome_theme-{{ version }}.tar.gz
  sha256: ff3ec7fec0f4c07982d1eaebb01f1c952d8bffba2b2a524cb4845d8ddf579e58

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - poetry
    - pip
  run:
    - python >=3.8
    - sphinx >=7.2.0,<7.3
    - beautifulsoup4 >=4.9.1,<5.0.0

test:
  imports:
    - sphinxawesome_theme
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://sphinxawesome.xyz
  summary: An awesome theme for the Sphinx documentation generator
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apmorton
